basic:
  # input file path
  input: input/text_demo_input.jsonl
  # save file path
  output: output/text_demo_output.jsonl
  # key in the input file corresponding to the value to extract/clean
  source_key: text
  # key in the output file for saving
  result_key: clean_content
  # Remove sentences that contain any of the following listed content
  pattern: [ "@article" ]
  cleaner_class: TextCleaner
TextCleaner:
  drop_docs_exceeding_newline_proportion:
  drop_doc_below_ratio:
  end_clip:
  remove_specific_patterns:
  remove_control_chars:
  remove_extraspace:
  remove_unwanted_lines: